- exchange/exchange.go
- exchange/exchange_test.go
> Update to upstream master

- config/config.go
- deploy/pid.go
- deploy/pid_test.go
- grace-shepherd.sh
- main.go
- server/server.go
- util.go
[PROG-1230](https://jira.tapjoy.net/browse/PROG-1230)
This PR adds graceful shutdown functionality that is compatible with our deployment procedures to the tpe_prebid_service project.
The workflow is as follows:
- When a backend service is initiated, it writes it's process id to a file (<process_id>.pid) in a folder (default is './pids' but that path is hardcoded in `grace-shepherd.sh` script,  therefore it would break the system if another value is assigned)
- When we want to deploy a new version of the service, `grace-shepherd.sh` script is run
- It first notifies the service by sending `-SIGUSR1` signal to the service.
- The service should be listening to this signal and gracefully shut itself down by closing all connections and ports securely, and finally raise the signal.
- Then the …
> [PROG-1230] Graceful shutdown

- adapters/liftoff/liftoff.go
- adapters/liftoff/liftoff_test.go
- adapters/liftoff/liftofftest/exemplary/endpoint_apac.json
- adapters/liftoff/liftofftest/exemplary/endpoint_empty.json
- adapters/liftoff/liftofftest/exemplary/endpoint_eu.json
- adapters/liftoff/liftofftest/exemplary/endpoint_not_supported.json
- adapters/liftoff/liftofftest/exemplary/endpoint_us_east.json
- adapters/liftoff/liftofftest/exemplary/orientation_horizontal.json
- adapters/liftoff/liftofftest/exemplary/orientation_vertical.json
- adapters/liftoff/liftofftest/exemplary/video_interstitial.json
- adapters/liftoff/liftofftest/exemplary/video_rewarded.json
- adapters/liftoff/usersync.go
- adapters/liftoff/usersync_test.go
- config/config.go
- deploy/local/manifest.yaml
- exchange/adapter_map.go
- openrtb_ext/bidders.go
- openrtb_ext/imp_liftoff.go
- router/router.go
- static/bidder-info/liftoff.yaml
- static/bidder-params/liftoff.json
- usersync/usersyncers/syncer.go
- usersync/usersyncers/syncer_test.go
[PROG-1289](https://jira.tapjoy.net/browse/PROG-1289)
This PR adds. Liftoff adapter to tpe-prebid-service project forked from Prebid Server. Because the documentation of the integration is not complete, this adapter will be needed to revisit when new information from Liftoff is received. Credentials values and endpoints are placeholders.
This adapter won't change the current functionality of tpe-prebid-service. It will continue to request only rubicon until the integration is completed.
- Pull branch
- Add debug logs to exchange/bidder.go line 303, just before making request (sorry, honeycomb is not integrated)
```
requestDump, err := httputil.DumpRequest(req, true)
if err != nil {
fmt.Println(err)
}
fmt.Println(string(requestDump))
```
- Make dev
- Forward …
> [PROG-1289] Liftoff adapter

- testdata/responses/liftoff/fill_high_bid.json
- testdata/responses/liftoff/fill_low_bid.json
No-JIRA
This PR updates liftoff responses to include imptrackers.
Please review: @eric-kansas
> [NO-JIRA] imptrackers in test files

- adapters/liftoff/liftoff.go
- adapters/liftoff/liftofftest/exemplary/endpoint_apac.json
- adapters/liftoff/liftofftest/exemplary/endpoint_empty.json
- adapters/liftoff/liftofftest/exemplary/endpoint_eu.json
- adapters/liftoff/liftofftest/exemplary/endpoint_not_supported.json
- adapters/liftoff/liftofftest/exemplary/endpoint_us_east.json
- adapters/liftoff/liftofftest/exemplary/orientation_horizontal.json
- adapters/liftoff/liftofftest/exemplary/orientation_vertical.json
- adapters/liftoff/liftofftest/exemplary/video_interstitial.json
- adapters/liftoff/liftofftest/exemplary/video_rewarded.json
NO-JIRA
This PR is to put rewarded flag in Imp->Ext for liftoff requests. We used to send it in Imp->Video->Ext, and it turned out to be wrong place.
Please review: @riteshnoronha @eric-kansas
> [NO-JIRA] Rewarded flag in imp->ext for liftoff

- adapters/moloco/moloco.go
Reverts Tapjoy/tpe_prebid_service#30
> Revert "[NO-JIRA] Moloco bid id"

- static/bidder-info/unicorn.yaml
NO-JIRA
This PR is to add Banner to Unicorn.yaml file. Currently following error is being reported by tpe_prebid_service.
```
"ext": {
"errors": {
"unicorn": [
{
"code": 2,
"message": "request.imp[0] uses banner, but this bidder doesn't support it"
}
]
}
}
```
This error doesn't have any effect, only reporting but it's good to fix it.
> [NO-JIRA] Unicorn Banner fix

- adapters/unicorn/unicorn.go
- adapters/unicorn/unicorntest/exemplary/endpoint_jp.json
- adapters/unicorn/unicorntest/exemplary/endpoint_not_supported.json
- adapters/unicorn/unicorntest/exemplary/video_interstitial.json
- adapters/unicorn/unicorntest/exemplary/video_rewarded.json
It seems that Unicorn expect our version of the bid request based on our documentation and we have implemented the bid request based on their provided request sample.
Unicorn have asked us to change to location from `imp[0].ext.reward` to `imp[0].video.ext.rewarded` 
Jira: https://tapjoy.atlassian.net/browse/TPE-152
> [TPE-152] Modify Unicorn bid request as per their requirements.

- exchange/bidder.go
NO-JIRA
This PR is to test SKAN v2.2 with a test device (advertising id = `A9688F3E-FCBD-4F26-9E97-1A1D137AF047`).
This PR needs to be deployed wide, and after testing is finished, needs to be reverted back.
Tested in k8s, it prints all requests and responses for the given device (not for a specific Bidder but all).
Please review: @melty710
> [NO-JIRA] SKAN request testing for a test device

- exchange/bidder.go
Reverts Tapjoy/tpe_prebid_service#55
Collected the needed requests so we can revert this now!
> Revert "[NO-JIRA] SKAN request testing for a test device"

- adapters/taurusx/taurusx.go
- adapters/taurusx/taurusxtest/exemplary/endpoint_jp.json
- adapters/taurusx/taurusxtest/exemplary/endpoint_not_supported.json
- adapters/taurusx/taurusxtest/exemplary/endpoint_sg.json
- adapters/taurusx/taurusxtest/exemplary/endpoint_us_east.json
- adapters/taurusx/taurusxtest/exemplary/video_interstitial.json
- adapters/taurusx/taurusxtest/exemplary/video_rewarded.json
https://tapjoy.atlassian.net/browse/NGS-387
This PR is to update MRAID logic for TaurusX to make them just like other Bidders. They used to look for api=[3,5] but then they asked us to send them both Video and Banner objects in the request.
> [NGS-387] TaurusX MRAID updates

- exchange/bidder.go
update dsp http wrappers to record raw responses when verbose tracing req
> [no-jira] Log verbose bidder requests

- exchange/bidder.go
Fix issue where request was getting additionally logged in response
> only add verbose attribute for events

- adapters/rubicon/rubicon.go
- cache/skanidlist/cfg/rubicon.go
- cache/skanidlist/client.go
https://tapjoy.atlassian.net/browse/NGS-415
This PR is to add SKAN logic for Rubicon, we'll start sending SKAN requests to Rubicon.
- AS: https://github.com/Tapjoy/ad_service/pull/823
- MBS: https://github.com/Tapjoy/mediation_bid_service/pull/737
> [NGS-415] Rubicon SKAN

- adapters/dv360/dv360.go
- adapters/dv360/dv360test/exemplary/app_banner.json
- adapters/dv360/dv360test/exemplary/app_banner_instl.json
- adapters/dv360/dv360test/exemplary/app_video_rewarded.json
- adapters/dv360/dv360test/exemplary/ip_truncated.json
- adapters/dv360/dv360test/exemplary/merged_device_ext.json
- adapters/dv360/dv360test/exemplary/pub_id.json
- adapters/dv360/dv360test/exemplary/skan_app_banner.json
- adapters/dv360/dv360test/exemplary/skan_app_banner_instl.json
- adapters/dv360/dv360test/exemplary/skan_video_interstitial.json
- adapters/dv360/dv360test/exemplary/skan_video_rewarded.json
- adapters/dv360/dv360test/exemplary/truncated_ipv4.json
- adapters/dv360/dv360test/exemplary/truncated_ipv6.json
- adapters/dv360/dv360test/exemplary/video_interstitial.json
- adapters/dv360/dv360test/exemplary/video_rewarded.json
- adapters/dv360/dv360test/supplemental/response_code_204.json
- adapters/dv360/dv360test/supplemental/response_code_400.json
- openrtb_ext/imp_dv360.go
https://tapjoy.atlassian.net/browse/NGS-477
This PR is to update publisher ID for Dv360 to use one coming from AS or MBS in impression extension struct.
- AS: https://github.com/Tapjoy/ad_service/pull/843
- MBS: https://github.com/Tapjoy/mediation_bid_service/pull/774
- go-prebid: https://github.com/Tapjoy/go-prebid/pull/55
> [NGS-477] Dv360 pub id update

- gdpr/impl.go
- gdpr/impl_test.go
NO-JIRA
This PR is to fix scrubbing conditions when there is a GDPR but no consent.
> [NO-JIRA] GDPR Scrub fix

- adapters/rubicon/rubicon.go
- adapters/rubiconmraid/rubiconmraid.go
add atts support to device.ext for rubicon and rubiconmraid
> add atts support to device.ext for rubicon and rubiconmraid

- adapters/mintegral/mintegral.go
- adapters/mintegral/mintegraltest/exemplary/endpoint_empty.json
- adapters/mintegral/mintegraltest/exemplary/endpoint_hk.json
- adapters/mintegral/mintegraltest/exemplary/endpoint_not_supported.json
- adapters/mintegral/mintegraltest/exemplary/endpoint_vg.json
- adapters/mintegral/mintegraltest/exemplary/orientation_horizontal.json
- adapters/mintegral/mintegraltest/exemplary/orientation_vertical.json
- adapters/mintegral/mintegraltest/exemplary/video_interstitial.json
- adapters/mintegral/mintegraltest/exemplary/video_rewarded.json
No-JIRA
This PR is to change Orientation from string to int as Mintegral requested. Values are:
```
VERTICAL_SCREEN = 1 
CROSS_CSREEN    = 2 
```
[Slack](https://tapjoy.slack.com/archives/C02A41FP1D2/p1631593095030600)
> [NO-JIRA] Mintegral Orientation

- adapters/pangle/pangle.go
- openrtb_ext/imp_pangle.go
- static/bidder-params/pangle.json
https://tapjoy.atlassian.net/browse/NGS-544
This PR is to add Pangle's US endpoint and multi endpoint support to Prebid. This is required to support rollout slowly on MBS and AS side.
> [NGS-544] Pangle new US endpoint and multi endpoint support

- adapters/bidder.go
- adapters/liftoff/liftoff.go
- exchange/bidder.go
- openrtb_ext/imp_liftoff.go
Add liftoff companion type support for html endcards
Additionally report status to honeycomb
> add companion type to liftoff supported requests

- adapters/pubmatic/pubmatic.go
- openrtb_ext/imp_pubmatic.go
Add site_id to both old and new flow for pubmatic
> add site id logic for pubmatic

- monitoring/newrelic/newrelic.go
- monitoring/newrelic/option.go
https://tapjoy.atlassian.net/browse/NGS-760
This PR is to disable NewRelic transaction tracer as requested.
- AS: https://github.com/Tapjoy/ad_service/pull/991
- MBS/TJX: https://github.com/Tapjoy/mediation_bid_service/pull/1119
- TPE: https://github.com/Tapjoy/tpe_prebid_service/pull/106
> [NGS-760] Disable NewRelic Transaction tracer

- static/bidder-info/rtbhouse.yaml
https://tapjoy.atlassian.net/browse/NGS-761
This PR is to support banner in rtbhouse yaml config even though we don't support it. Otherwise request just fails.
> [NGS-761] RTBHouse banner

- adapters/pubmatic/pubmatic.go
https://tapjoy.atlassian.net/browse/NGS-796
This PR is to update Pubmatic $5 experiment for US. We're increasing it to $10
> [NGS-796] Pubmatic 10$ bidfloors

- adapters/operaads/operaads.go
- adapters/operaads/operaadstest/supplemental/status_204.json
- adapters/operaads/operaadstest/supplemental/status_205.json
- adapters/operaads/operaadstest/supplemental/status_400.json
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
Include Video and Banner objects to be included in same request
Assigns default bidType to Video. Side effects of this will be monitored.
Jira: https://tapjoy.atlassian.net/browse/NGS-815
> [NGS-815] Update OperaAds Adapter To Include Video/Banner To Be In Same Request

- adapters/tapjoy/tapjoy.go
- adapters/tapjoy/tapjoytest/exemplary/video_rewarded.json
- adapters/tapjoy/tapjoytest/exemplary/video_rewarded_with_nbr.json
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
- openrtb_ext/imp_tapjoy.go
https://tapjoy.atlassian.net/browse/NGS-863
Reverts Tapjoy/tpe_prebid_service#120
> Revert "[NGS-847] Enable OPTSOA to use BFS bid floor"

- deploy/kubernetes/base/app.yaml
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
See related PR https://github.com/Tapjoy/placement_service/pull/1217. This is a downstream deep dependency (via `ad_service`) of `placement_service`.
> OPER-6076 Decrease ndots

- deploy/kubernetes/overlays/legacy-production-eks/web-internal/app-patch.yaml
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
Also moving to the node-local tracing endpoint.
> OPER-5261 Remove OptSOA env var 'gift'

- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
Empty deploy to sync TPE with updated Chef config changes
> Empty Deploy

- deploy/kubernetes/overlays/legacy-production-eks/web-internal/hpa.yaml
This is a comment no-op, and I will be merging it directly.
> OPER-6133 Leave breadcrumb comment

- adapters/tjx_operaads/operaads.go
- adapters/tjx_operaads/operaadstest/exemplary/endpoint_apac.json
- adapters/tjx_operaads/operaadstest/exemplary/endpoint_empty.json
- adapters/tjx_operaads/operaadstest/exemplary/endpoint_eu.json
- adapters/tjx_operaads/operaadstest/exemplary/endpoint_not_supported.json
- adapters/tjx_operaads/operaadstest/exemplary/endpoint_us_east.json
- adapters/tjx_operaads/operaadstest/exemplary/orientation_horizontal.json
- adapters/tjx_operaads/operaadstest/exemplary/orientation_vertical.json
- adapters/tjx_operaads/operaadstest/exemplary/video.json
- adapters/tjx_operaads/operaadstest/exemplary/video_interstitial.json
- adapters/tjx_operaads/operaadstest/exemplary/video_rewarded.json
- adapters/tjx_operaads/operaadstest/supplemental/status_204.json
- adapters/tjx_operaads/operaadstest/supplemental/status_205.json
- adapters/tjx_operaads/operaadstest/supplemental/status_400.json
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
##Jira
https://tapjoy.atlassian.net/browse/NGS-958?focusedCommentId=135742
> [NGS-958] Send blank req.imp[].tagid value for OperaAds

- adapters/tjx_youappi/youappi.go
- adapters/tjx_youappi/youappitest/exemplary/endpoint_apac.json
- adapters/tjx_youappi/youappitest/exemplary/endpoint_empty.json
- adapters/tjx_youappi/youappitest/exemplary/endpoint_eu.json
- adapters/tjx_youappi/youappitest/exemplary/endpoint_not_supported.json
- adapters/tjx_youappi/youappitest/exemplary/endpoint_us_east.json
- adapters/tjx_youappi/youappitest/exemplary/video_interstitial.json
- adapters/tjx_youappi/youappitest/exemplary/video_rewarded.json
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
This PR populates the imp[0].ext.rewarded flag for YouAppi.
[NGS-1021](https://tapjoy.atlassian.net/browse/NGS-1021)
> [NGS-1021] Implemented YouAppi rewarded flag

- .github/workflows/security.yml
- adapters/bidder.go
- adapters/tjx_liftoff/liftoff.go
- exchange/bidder.go
- openrtb_ext/request.go
This task is to support multiple bid request. Currently, this is just a POC which is required for Liftoff Experiment.
TJX: https://github.com/Tapjoy/mediation_bid_service/pull/1436
TPE: https://github.com/Tapjoy/tpe_prebid_service/pull/156
go-prebid: https://github.com/Tapjoy/go-prebid/pull/101
TBD
Jira: https://tapjoy.atlassian.net/browse/NGS-987
> [NGS-987] Multiple bid request for Liftoff

- adapters/tjx_liftoff/liftoff.go
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
Corrected the bid floor index for correct bid floor
> [NGS-987] Corrected the bid floor value index

- adapters/tjx_operaads/operaads.go
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
Added Skadn ids for Operaads
https://tapjoy.atlassian.net/browse/NGS-1058
> [NGS-1058] Added Skadn ids for operaads

- adapters/tjx_liftoff/liftoff.go
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
Added 8 requests for Liftoff multi bid experiment
TJX: https://github.com/Tapjoy/mediation_bid_service/pull/1455
TPE: https://github.com/Tapjoy/tpe_prebid_service/pull/159
`./validate.sh` and `make build` yields no errors
Jira: https://tapjoy.atlassian.net/browse/NGS-1061
> [NGS-1061] Added eight request for liftoff experiment

- adapters/tjx_liftoff/liftoff.go
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
- exchange/bidder.go
With this change there will be 8 Request per auction request.
Jira: https://tapjoy.atlassian.net/browse/NGS-1066
> [NGS-1066] Added request for iOS vs Android

- adapters/tjx_liftoff/liftoff.go
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
Updated Bid floor for liftoff experiment.
https://tapjoy.atlassian.net/browse/NGS-1074
> [NGS-1074] Updated Liftoff Experiment bid floors]

- adapters/tjx_liftoff/liftoff.go
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
Updated the floors and removed iOS rewarded vast as it was not performing well.
https://tapjoy.atlassian.net/browse/NGS-1079
> [NGS-1079] Update the Liftoff bid floors for multi bid experiment

- adapters/tjx_operaads/operaads.go
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
https://tapjoy.atlassian.net/browse/NGS-1076
This PR is to add new skan IDs for operaads.
> [NGS-1076] Additional SKAN IDs for operaads

- adapters/bidder.go
- adapters/tjx_liftoff/liftoff.go
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
- exchange/bidder.go
- openrtb_ext/request.go
This PR is for running two experiments :
1. Passing BFS floor and passing $1, $2, and $3 increments, totaling 4 requests.
2. Passing Mediator floor and passing $1, $2,  and $3 increments so total 4 requests.
Go-prebid: https://github.com/Tapjoy/go-prebid/pull/105
TPE: https://github.com/Tapjoy/tpe_prebid_service/pull/168
TJX: https://github.com/Tapjoy/mediation_bid_service/pull/1478
`./validate.sh` and `make build` yields no error
Jira:  https://tapjoy.atlassian.net/browse/NGS-1082
> [NGS-1082] Liftoff experiment for BFS and mediator bif floor

- adapters/tjx_liftoff/liftoff.go
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
Unmarshalling the liftoff extension correctly if the response does not have any extension
> [NO-JIRA] Fixing the issue with liftoff unmarshalling
