- config/config.go
- router/router.go
[PROG-1256](https://jira.tapjoy.net/browse/PROG-1256)
This PR changes the `status` endpoint to `healthz` which is `tapjoy standard`. Also the default value is updated so that the endpoint responds with `"OK"`.
Please review: @eric-kansas, @jingniwei, @alanbrent
- Run the tpe_prebid_service locally. Until merging [@jingniwei 's PR](https://github.com/Tapjoy/tpe_prebid_service/pull/3):
- `go build`
- `./prebid-server`
- Curl `healthz` endpoint
- `curl "http://localhost:8000/healthz"`
- Confirm if you get `"OK"`response back
> [PROG-1256] Change status endpoint to healthz

- Dockerfile
- Makefile
- deploy/build
_Contributes to [OPER-5109](https://jira.tapjoy.net/browse/OPER-5109)_
This PR adds some standardized plumbing to the build process to allow us to actually deploy this project.
I've used one of our more recent Golang projects, https://github.com/Tapjoy/tap-survey-demand, as a reference for Go specifics.
> (OPER-5109) Add slug building

- Procfile
- deploy/upstart-templates/process.conf.erb
These are copied from other go projects, ad service as an example contain these files that are necessary for upstart to work properly.
> Adding deployment scaffolding for project

- static/bidder-info/rubicon.yaml
[PROG-1259](https://jira.tapjoy.net/browse/PROG-1259)
This PR adds `video` to rubicon's config for app type requests (app is for mobile, site is for browser) to enable us to request video ads from rubicon.
Note that `adapters.rubicon.xapi.password`, `adapters.rubicon.xapi.username` and `adapters.rubicon.disabled` are also needed to be set, we're handling in chef config : https://github.com/Tapjoy/5rocks-chef/pull/2605
Please review: @eric-kansas
> [PROG-1259] Enable rubicon video

- adapters/rubicon/rubicon.go
- deploy/local/manifest.yaml
- go.sum
[PROG-1273](https://jira.tapjoy.net/browse/PROG-1273)
This PR adds support for AqID field coming in rubicon response. Rubicon returns this value, but because openrtb2.5 BidResponse object doesn't have this field, it disappears when Unmarshalling rubicon response into openrtb2.5 BidResponse. With this PR, we unmarshal the response into our custom rubicon struct to extract aqid, then inject the aqid into bid.ext object.
Please see [ad_service PR](https://github.com/Tapjoy/ad_service/pull/555)
- [ad_service PR](https://github.com/Tapjoy/ad_service/pull/555)
- [go-prebid PR](https://github.com/Tapjoy/go-prebid/pull/4)
> [PROG-1273] AqID support

- adapters/rubicon/rubicon.go
- openrtb_ext/imp_rubicon.go
[PROG-1273](https://jira.tapjoy.net/browse/PROG-1273)
This PR adds support for:
- req.imp[0].ext.viewabilityvendors (e.g. "moat.com")
- req.imp[0].ext.rp.target.moat_certified (true/false)
- req.imp[0].ext.rp.target.SDKVersion (e.g. "13.3.1")
See [ad_service PR](https://github.com/Tapjoy/ad_service/pull/557)
- [ad_service PR](https://github.com/Tapjoy/ad_service/pull/557)
- [go-prebid PR](https://github.com/Tapjoy/go-prebid/pull/6)
> [PROG-1273] Viewability vendors support

- endpoints/openrtb2/auction.go
- exchange/exchange.go
- exchange/exchange_test.go
- monitoring/newrelic/newrelic.go
[PROG-1287](https://jira.tapjoy.net/browse/PROG-1287)
This PR adds NewRelic error reporting functionality to tpe_prebid_service project. Also, recovering from panic is also added.
- Update manifest
- PBS_MONITORING_NEWRELIC_LICENSE_KEY: {{ default "bb8353602ba48d962a5db59ac4e1468d2da7fb8d" (env "PBS_MONITORING_NEWRELIC_LICENSE_KEY") | quote }}
- PBS_ADAPTERS_RUBICON_XAPI_USERNAME: "tapjoy"
- PBS_ADAPTERS_RUBICON_XAPI_PASSWORD: "QD054DGVKH"
- insert nil pointer bugs or make some functions return error in the code to confirm if they are handled correctly and reported to NewRelic
- make dev
- forward ports
- kubectl port-forward tpe-prebid-service 8000
- run postman request `http://localhost:8000/openrtb2/auction`
- check logs and NR dashboard
> [PROG-1287] NewRelic error reporting

- exchange/bidder.go
- exchange/exchange.go
- exchange/exchange_test.go
No-JIRA
This PR fixes newrelic goroutine transaction segment ending error. This is not an error we get currently in production because we didn't start calling more than 1 dsp. But this error was discovered during tests.
- In current master, make dev
- run test request to call rubicon and liftoff at the same time (testdata/scenarios/rubicon_fill_liftoff_fill_liftoff_wins) couple times
- confirm from k8s logs that we're getting segment ending error for some requests.
- run these steps after pulling the branch and confirm that we no longer get that error
> [NO-JIRA] NR goroutine fixes

- router/router.go
NO-JIRA
This PR is to fix `Method Not Allowed` errors for HEAD health checks, which started to be reported after this change : https://github.com/Tapjoy/5rocks-chef/pull/2703
Although @alanbrent told that it's not super required, I missed the good old days of tpe_prebid_service where error rate is ~0%, so I decided to add this support.
- pull the branch
- spin up k8s tpe-prebid-service pod
```
curl -i -X HEAD http://tpe-prebid-service.default.svc.cluster.local/healthz
```
This should return HTTP 200, with OK message.
> [NO-JIRA] Support HEAD requests for healthz

- adapters/moloco/moloco.go
NO-JIRA
This PR is to set bid_id in the response->seatbid->bid object to response id if it's 1. Moloco is sending bid_id = 1 always, to be able to distinguish different bids, we're doing this.
> [NO-JIRA] Moloco bid id

- adapters/crossinstall/crossinstall.go
- adapters/liftoff/liftoff.go
- adapters/moloco/moloco.go
- adapters/openrtb_util.go
- adapters/rubicon/rubicon.go
- adapters/taurusx/taurusx.go
NO-JIRA
This PR is to update filtering logic by using downcased version of the IDs. Originally, it was assumed that the incoming SKAN ID list is already lowercased but it was figured out that it's not the case. So filtering logic wasn't working properly. Comparison must be done by lowercasing the SKAN ID, and the original value in the list should be passed.
> [NO-JIRA] SKAN downcase trouble

- adapters/crossinstall/crossinstall.go
- adapters/liftoff/liftoff.go
- adapters/moloco/moloco.go
- adapters/taurusx/taurusx.go
- adapters/unicorn/unicorn.go
[TPE-137](https://tapjoy.atlassian.net/browse/TPE-137)
This PR is to add custom close button disable support for our DSP partners, especially for Liftoff.
We're testing MRAID with Liftoff, but creative team warned us that MRAID ads come with custom close button, so when they put Tapjoy's close button too, it looks bad.
We investigated the issue and asked questions to Liftoff, and learned that they're respecting `allowcustomclosebutton` field in banner->ext. Therefore, with this PR, we'll always be passing `false` to disable custom close button.
Note that this feature is implemented for all currently integrated DSPs but Rubicon, because Rubicon has a custom XAPI that doesn't support this flag. MRAID for Rubicon is not in out plans anyway.
This feature will be default for the following DSP …
> [TPE-37] Custom close button disable support for banner

- adapters/taurusx/taurusx.go
- cache/skanidlist/cache.go
- cache/skanidlist/client.go
- cache/skanidlist/model/skanidlist.go
- cache/skanidlist/response.go
- cache/skanidlist/util.go
- exchange/bidder.go
- exchange/bidder_validate_bids.go
- exchange/bidder_validate_bids_test.go
- exchange/exchange.go
- exchange/exchange_test.go
- exchange/legacy.go
https://tapjoy.atlassian.net/browse/NGS-260
This PR is to add support for Multiple SKAN ID Lists for SSPs.
Currently, each Bidder has a single SKAN ID. But some Bidders (SSPs like Rubicon, PubMatic, TaurusX etc.) needs to provide a list of SKAN IDs and Tapjoy needs to use that list when making their individual Bidder requests. Bidders who support this feature are hosting the list as json or xml on their servers and provides URL for us to fetch from. Details of it can be found here: https://docs.google.com/document/d/18DESlWha9OD_7E3iSpfz9r7qdb52LHNhjF_GC6Sz20A/edit?usp=sharing
This implementation has monitoring around the fetching calls and reports to NR if fetching fails. Flow is as follows:
- Before making individual requests for bidders, call client's Update function to fetch files …
> [NGS-260] Support for multiple SKAN ID Lists - 2

- cache/skanidlist/cache.go
- cache/skanidlist/cfg/cfg.go
- cache/skanidlist/cfg/pubmatic.go
- cache/skanidlist/cfg/taurusx.go
- cache/skanidlist/client.go
https://tapjoy.atlassian.net/browse/NGS-260
This PR is a fix for SKAN ID list client synchronization upon testing requirements of PubMatic.
First of all, thanks @shahbaztariq for detecting this issue and working on a fix, appreciate it!
Summary of the issue is, we wanted to test PubMatic req/resps with SKADN. Because we use a singleton for SKAN cache clients, first call would fetch the list from server in a goroutine so first Get call gets an empty list until the HTTP call response after ~300ms. However we needed consistent testing, so we decided to initialize Bidder SKAN ID List caches with Bidder's single SKAN ID. When we wanted to do it, we saw that it created a race condition because the `getting the client` isn't thread safe even though every `write to cache` and `read from cache` is …
> [NGS-260] SKAN ID List Client Sync

- adapters/openrtb_util.go
- openrtb_ext/imp.go
- testdata/responses/liftoff/fill_high_bid_mraid_skadn_2_2.json
- testdata/responses/liftoff/fill_high_bid_skadn_2_2.json
https://tapjoy.atlassian.net/browse/NGS-329
This PR is to add Versions array to SKADN data to support SKAN version 2.2. Also it updates the values in SKAN version 2.2 test files to have correct types.
Fired an Easy App request with SDK 12.8.1 and device 14.4. Printed DSP requests in tpe_prebid_service pod. Confirmed we have Versions in the request for DSPs whose SKAN IDs in the info.plist.
> [NGS-329] Versions for SKAN 2.2

- adapters/dv360/dv360.go
- adapters/dv360/dv360test/exemplary/app_banner.json
- adapters/dv360/dv360test/exemplary/app_banner_instl.json
- adapters/dv360/dv360test/exemplary/app_video_instl.json
- adapters/dv360/dv360test/exemplary/app_video_rewarded.json
- adapters/dv360/dv360test/exemplary/ip_truncated.json
- adapters/dv360/dv360test/exemplary/merged_device_ext.json
- adapters/dv360/dv360test/exemplary/skan_app_banner.json
- adapters/dv360/dv360test/exemplary/skan_app_banner_instl.json
- adapters/dv360/dv360test/exemplary/skan_video_interstitial.json
- adapters/dv360/dv360test/exemplary/skan_video_rewarded.json
- adapters/dv360/dv360test/exemplary/truncated_ipv4.json
- adapters/dv360/dv360test/exemplary/truncated_ipv6.json
- adapters/dv360/dv360test/exemplary/video_interstitial.json
- adapters/dv360/dv360test/exemplary/video_rewarded.json
- adapters/dv360/dv360test/supplemental/response_code_204.json
- adapters/dv360/dv360test/supplemental/response_code_400.json
https://tapjoy.atlassian.net/browse/NGS-477
This PR is to overwrite req->app->publisher->id field with Tapjoy's id in apps-ads.txt id (`1011b04a93164a6db3a0158461c82433`). Currently we're using request's app's publisher's encrypted ID but Google is complaining about this as it's stated in the IAB contract (https://iabtechlab.com/wp-content/uploads/2019/03/IAB-OpenRTB-Ads.txt-Public-Spec-1.0.2.pdf)
We'll talk to the other Bidders and fix this globally if necessary. For now, it's Google DV360 only.
Tested locally in k8s that we're overwriting this field only for Google DV360 with the value specified.
> [NGS-477] DV360 publisher.id overwrite

- gdpr/impl.go
- gdpr/impl_test.go
No-JIRA
After we merged the prebid sync PR, we realized that the new code stopped supporting TCF 1.1 and defaulted to TCF 2.0 which we haven't supported yet. As a result of this change, all our GDPR requests started to be blocked. This PR is a workaround to stop blocking GDPR requests and if there is no consent, apply scrubbing device and geo, just like before the change.
We'll revisit here and remove this hack once we have TCF 2.0 support.
> [NO-JIRA] GDPR Hack until supporting TCF 2.0

- static/bidder-info/rubiconmraid.yaml
https://tapjoy.atlassian.net/browse/NGS-295
This PR is to enable video for Rubicon MRAID in bidder info yaml file. Prebid request has Video and Banner objects in the same impression object. When Rubicon MRAID bidder doesn't support Video, in prebid response, there is an error that says this even though it calls the endpoint and gets the response. This is opens circuit breaker on MBS because if the prebid response has errors for specific bidder, it counts that response as circuit breaker fail. We need to enable it, we'll be removing when making the request anyway.
> [NGS-295] Enable video for Rubicon MRAID

- endpoints/openrtb2/auction.go
parse header value in nanoseconds;
if tMax is less than or equal to 0 return
Relates to: https://github.com/Tapjoy/go-prebid/pull/69
> parse heading in nanoseconds; if tMax is less than or equal to 0 return immediately 

- adapters/mintegral/mintegral.go
- adapters/mintegral/mintegraltest/exemplary/endpoint_empty.json
- adapters/mintegral/mintegraltest/exemplary/endpoint_hk.json
- adapters/mintegral/mintegraltest/exemplary/endpoint_not_supported.json
- adapters/mintegral/mintegraltest/exemplary/endpoint_vg.json
- adapters/mintegral/mintegraltest/exemplary/orientation_horizontal.json
- adapters/mintegral/mintegraltest/exemplary/orientation_vertical.json
- adapters/mintegral/mintegraltest/exemplary/video_interstitial.json
- adapters/mintegral/mintegraltest/exemplary/video_rewarded.json
- adapters/mintegral/mintegraltest/exemplary/video_rewarded_header_bidding_programmatic.json
- adapters/mintegral/mintegraltest/exemplary/video_rewarded_header_bidding_waterfall.json
- adapters/moloco/moloco.go
- adapters/moloco/molocotest/exemplary/endpoint_apac.json
- adapters/moloco/molocotest/exemplary/endpoint_empty.json
- adapters/moloco/molocotest/exemplary/endpoint_eu.json
- adapters/moloco/molocotest/exemplary/endpoint_not_supported.json
- adapters/moloco/molocotest/exemplary/endpoint_us_east.json
- adapters/moloco/molocotest/exemplary/video_interstitial.json
- adapters/moloco/molocotest/exemplary/video_rewarded.json
- adapters/moloco/molocotest/exemplary/video_rewarded_header_bidding_programmatic.json
- adapters/moloco/molocotest/exemplary/video_rewarded_header_bidding_waterfall.json
- openrtb_ext/imp_mintegral.go
- openrtb_ext/imp_moloco.go
https://tapjoy.atlassian.net/browse/NGS-606
This PR is to add HeaderBidding flag and encrypted MediatorID to all DSPs' requests. Currently it's only Moloco and Mintegral. This is just a cleanup PR for this repo. As we're passing these values in source->ext (standard field), they're being handled automatically, no need to do any change here.
HoneyComb
- MBS: https://github.com/Tapjoy/mediation_bid_service/pull/1038
- AS: https://github.com/Tapjoy/ad_service/pull/954
- go-prebid: https://github.com/Tapjoy/go-prebid/pull/79
- tpe-prebid: https://github.com/Tapjoy/tpe_prebid_service/pull/100
> [NGS-606] HeaderBidding flag and MediatorID in all DSP requests

- adapters/pubmatic/pubmatic.go
Based on discussions with pubmatic, it was inferred that TJ bid floors are too low and hence their bidder considers our traffic of low value, then decides to no-bid or underbid. 
IS has provided some insight that we probably need to set static floors for brand dsp’s like pubmatic to get the bidder to recognize supply as valid.
As a test for all pubmatic US traffic, we would set the floor as 5$.  The logic will be as follows.
For all pubmatic US traffic, if the incoming bid-floor is below 5$, we set it to 5$
For all pubmatic US traffic, if the incoming bid-floor is above 5$, we will pass that as is.
JIRA: https://tapjoy.atlassian.net/browse/NGS-757
> add minimum floor of 5.0 for pubmatic requests

- Dockerfile
- Makefile
- deploy/build
- deploy/kubernetes/base/app.yaml
- deploy/kubernetes/base/kustomization.yaml
- deploy/kubernetes/components/tooling/production/entrypoint-aws.sh
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/app-patch.yaml
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/hpa.yaml
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
- deploy/kubernetes/overlays/localdev/web-internal/app-patch.yaml
- deploy/kubernetes/overlays/localdev/web-internal/kustomization.yaml
This changeset runs successfully in EKS and a slug continues to build.
We are planning to add MBS back to production next. This means that the engineers deploying changes to this repo will now have 2 production approval phases. The first one is EKS-based Kubernetes infra, and the second one the EC2-based infra.
> OPER-6066 Put app in production Kubernetes

- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
- deploy/systemd-templates/process.service.erb
Unfortunately systemd breaks previously-orthogonal relationships, and even though we set appropriate user limits in Chef systemd doesn't respect them.
From a prod box currently:
```
Mar  4 00:15:00 ip-172-16-10-216 tpe_prebid_service-web[1]: E0304 00:15:00.718336    6128 listener.go:44] Error accepting connection: accept tcp [::]:8000: accept4: too many open files
Mar  4 00:15:00 ip-172-16-10-216 tpe_prebid_service-web[1]: 2022/03/04 00:15:00 http: Accept error: accept tcp [::]:8000: accept4: too many open files; retrying in 5ms
Mar  4 00:15:00 ip-172-16-10-216 tpe_prebid_service-web[1]: E0304 00:15:00.723527    6128 listener.go:44] Error accepting connection: accept tcp [::]:8000: accept4: too many open files
Mar  4 00:15:00 ip-172-16-10-216 tpe_prebid_service-web[1]: 2022/03/04 00:15:00 …
```
> Increase limits in systemd template

- deploy/kubernetes/overlays/legacy-production-eks/web-internal/app-patch.yaml
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
I missed this in the logs
```
2022/03/04 19:55:07 traces exporter is disconnected from the server localhost:4139: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4139: connect: connection refused"
```
> OPER-6066 Override otelcol endpoint

- adapters/tapjoy/tapjoy.go
- adapters/tapjoy/tapjoytest/exemplary/video_rewarded.json
- adapters/tapjoy/tapjoytest/exemplary/video_rewarded_with_nbr.json
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
- openrtb_ext/imp_tapjoy.go
Enabled OPTSOA to use BFS bid floor only
TJX: https://github.com/Tapjoy/mediation_bid_service/pull/1211
TPE: https://github.com/Tapjoy/tpe_prebid_service/pull/120
`make build` yields no errors
Jira: https://tapjoy.atlassian.net/browse/NGS-847
> [NGS-847] Enable OPTSOA to use BFS bid floor

- deploy/kubernetes/base/app.yaml
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/app-patch.yaml
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
The default is 30, which creates a race condition between our standard lifecycle routines that involve a `sleep 30`.
Also including some readability fixes around lifecycle routines.
> OPER-5261 Increase termination grace period

- adapters/tapjoy/tapjoy.go
- adapters/tapjoy/tapjoytest/exemplary/video_rewarded.json
- adapters/tapjoy/tapjoytest/exemplary/video_rewarded_with_nbr.json
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
- openrtb_ext/imp_tapjoy.go
Cleanup PR to remove deprecated Tapjoy bid floor logic that existed before NGS-833 DSP Bid Floor change.
`make build` and `./validate.sh`
local end to end testing to make sure bid floor values come through for Tapjoy bidder
`make build` and `./validate.sh`
end to end testing
Jira: https://tapjoy.atlassian.net/browse/NGS-887
Go Prebid: https://github.com/Tapjoy/go-prebid/pull/93
TPE: https://github.com/Tapjoy/tpe_prebid_service/pull/127/files
MBS: https://github.com/Tapjoy/mediation_bid_service/pull/1241
> [NGS-887] Move Tapjoy Logic Into DSP Bid Floor Support

- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
- opentelemetry.go
Honeycomb logging was missing root spans for requests. After looking into this, we theorized that the Otel sampling logic for TJX and TPE might be causing noop root spans to propogate down from TJX to TPE. Noop spans were not handled correctly in TPE and created independent child spans to be created with missing parent spans.
With this change, we updated TPE to use composite based logic. TPE tries creating a child span from the parent span, and if that does not exist, will default back to ratio based logic with ratio set to 0.0.
> [NO-JIRA] Update Otel Sampler Logic

- adapters/tjx_operaads/operaads.go
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
https://tapjoy.atlassian.net/browse/NGS-920
This PR is to overwrite OperaAds' Banner W & H with the default values that they provided:
- Phone: 320x480 (V), 480x320 (H)
- Tablet: 768x1024 (V), 1024x768 (H)
- [Phone/Horizontal](https://ui.honeycomb.io/tapjoy/datasets/mediation-bid-service/result/m6PSzdCicNe/trace/58Cs8Vy1RyV?span=8fe7e26e3e461e30)
- [Tablet/Horizontal](https://ui.honeycomb.io/tapjoy/datasets/mediation-bid-service/result/m6PSzdCicNe/trace/51TwCaZLhAm?span=a3d18c6eb87d7277)
- [Tablet/Vertical](https://ui.honeycomb.io/tapjoy/datasets/mediation-bid-service/result/dWgLf6xPhcX/trace/GcuD4iZAW2c?span=7fd937852a4ddffe)
- [Phone/Vertical](https://ui.honeycomb.io/tapjoy/datasets/mediation-bid-service/result/p4EXwuEuPXK/trace/t3J7Q6xHj3r?span=e50b27a43b1b1638)
Please check banner W …
> [NGS-920] OperaAds banner sizes

- Makefile
- deploy/kubernetes/base/app.yaml
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/hpa.yaml
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
This is a cost saving measure while we are not serving production traffic in EKS.
> OPER-6133 Scale down and roll out quickly for now

- adapters/tjx_operaads/operaads.go
- adapters/tjx_operaads/operaadstest/exemplary/endpoint_apac.json
- adapters/tjx_operaads/operaadstest/exemplary/endpoint_empty.json
- adapters/tjx_operaads/operaadstest/exemplary/endpoint_eu.json
- adapters/tjx_operaads/operaadstest/exemplary/endpoint_not_supported.json
- adapters/tjx_operaads/operaadstest/exemplary/endpoint_us_east.json
- adapters/tjx_operaads/operaadstest/exemplary/orientation_horizontal.json
- adapters/tjx_operaads/operaadstest/exemplary/orientation_vertical.json
- adapters/tjx_operaads/operaadstest/exemplary/video.json
- adapters/tjx_operaads/operaadstest/exemplary/video_interstitial.json
- adapters/tjx_operaads/operaadstest/exemplary/video_rewarded.json
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
Passing Rewarded Flag in video extension 
`./validate.sh` and `make build` yield no error
HC: https://ui.honeycomb.io/tapjoy/datasets/mediation-bid-service/result/HxreZWEWwP8/trace/w34KR2nRYEV?span=d8264179427496c5
Jira: https://tapjoy.atlassian.net/browse/NGS-931
> [NGS-931] Added rewarded flag to video extensions

- adapters/tjx_liftoff/liftoff.go
- adapters/tjx_liftoff/liftofftest/exemplary/endpoint_apac.json
- adapters/tjx_liftoff/liftofftest/exemplary/endpoint_empty.json
- adapters/tjx_liftoff/liftofftest/exemplary/endpoint_eu.json
- adapters/tjx_liftoff/liftofftest/exemplary/endpoint_not_supported.json
- adapters/tjx_liftoff/liftofftest/exemplary/endpoint_us_east.json
- adapters/tjx_liftoff/liftofftest/exemplary/orientation_horizontal.json
- adapters/tjx_liftoff/liftofftest/exemplary/orientation_vertical.json
- adapters/tjx_liftoff/liftofftest/exemplary/video_interstitial.json
- adapters/tjx_liftoff/liftofftest/exemplary/video_rewarded.json
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
- openrtb_ext/imp_tjx_liftoff.go
https://tapjoy.atlassian.net/browse/NGS-965
This PR is to make HTMLEndcard support default for Liftoff. This change includes removal of all HTMLEndcard support checks and adding `2` into video->companion_type always.
> [NGS-965] Liftoff HTML endcard 100%

- Makefile
Cleaning up the images is a nice-to-have, not a failure.
> Make artifact cleanup failures acceptable

- adapters/tjx_liftoff/liftoff.go
- deploy/kubernetes/overlays/legacy-production-eks/web-internal/kustomization.yaml
Passed Bid Response extension correctly while unmarshalling the bid response extensions.
`./validate.sh` and `make build` yields no error
HC: https://ui.honeycomb.io/tapjoy/datasets/mediation-bid-service/result/i5J9HXGXN29/trace/3rKjGTJsevC?fields[]=c_name&span=2dc0f1d00129b9df
Jira: https://tapjoy.atlassian.net/browse/NGS-1081
> [NGS-1081] Fixed Liftoff bid response extension
